import { mkdir, readFile, writeFile } from "node:fs/promises"
import { createServer } from "node:net"
import { join } from "node:path"

import { log } from "./log"
import { writeReportToolName } from "./report"
import type { ReportRuntime } from "./report-runtime"
import { opencodeConfigDir } from "./workspace"

export const reportUrlEnv = "CONVOY_REPORT_URL"
export const reportTokenEnv = "CONVOY_REPORT_TOKEN"

export type ReportBridge = {
  url: string
  token: string
  close(): void
}

export type StartReportBridgeOptions = {
  /** Resolved after OpenCode starts, before any executor session is created. */
  reports: () => ReportRuntime | undefined
  hostname?: string
}

/** Starts the authenticated loopback hop used by OpenCode's write_report shim. */
export async function startReportBridge(options: StartReportBridgeOptions): Promise<ReportBridge> {
  const token = crypto.randomUUID()
  const hostname = options.hostname ?? "127.0.0.1"
  const port = await freePort(hostname)
  const server = Bun.serve({
    hostname,
    port,
    idleTimeout: 0,
    fetch: (request) => handleReport(request, options.reports, token),
  })
  const url = `http://${hostname}:${server.port}/report`
  log.info(`[report] bridge listening at ${url}`)
  return { url, token, close: () => server.stop(true) }
}

async function handleReport(request: Request, reports: (() => ReportRuntime | undefined) | ReportRuntime, token: string): Promise<Response> {
  const runtime = typeof reports === "function" ? reports() : reports
  if (request.method !== "POST") return new Response("method not allowed", { status: 405 })
  if (request.headers.get("authorization") !== `Bearer ${token}`) return new Response("unauthorized", { status: 401 })
  let body: { sessionID?: unknown; payload?: unknown }
  try {
    body = (await request.json()) as typeof body
  } catch {
    return new Response("invalid json", { status: 400 })
  }
  const sessionID = typeof body.sessionID === "string" ? body.sessionID : ""
  if (!sessionID) return new Response("sessionID required", { status: 400 })
  const handle = runtime?.handleFor(sessionID)
  if (!handle) return new Response("unknown report session", { status: 404 })
  const result = await handle.write(body.payload)
  if ("error" in result) return Response.json(result, { status: 400 })
  return Response.json({ message: "Report saved.", chars: result.markdown.length })
}

async function freePort(hostname: string): Promise<number> {
  return await new Promise<number>((resolve, reject) => {
    const probe = createServer()
    probe.once("error", reject)
    probe.listen(0, hostname, () => {
      const address = probe.address()
      if (!address || typeof address === "string") {
        probe.close()
        reject(new Error("couldn't find a free port for the report bridge"))
        return
      }
      probe.close(() => resolve(address.port))
    })
  })
}

/** Materializes the write_report shim before OpenCode scans OPENCODE_CONFIG_DIR. */
export async function installWriteReportTool(options: { url?: string; token?: string; dir?: string } = {}): Promise<string> {
  const dir = options.dir ?? opencodeConfigDir()
  const toolsDir = join(dir, "tools")
  await mkdir(toolsDir, { recursive: true, mode: 0o700 })
  const path = join(toolsDir, `${writeReportToolName}.ts`)
  const source = options.url && options.token ? writeReportToolSourceWith(options.url, options.token) : fallbackWriteReportToolSource
  const existing = await readFile(path, "utf8").catch(() => undefined)
  if (existing !== source) await writeFile(path, source, { mode: 0o600 })
  return path
}

function writeReportToolSourceWith(url: string, token: string): string {
  return writeReportToolSource(JSON.stringify(escapeForSource(url)), JSON.stringify(escapeForSource(token)))
}

function escapeForSource(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$")
}

function writeReportToolSource(url: string, token: string): string {
  return `// Generated by Convoy. Do not edit: it is rewritten on every run.
import { tool } from "@opencode-ai/plugin"
export default tool({
  description: "Persist this phase's complete Markdown report through Convoy. Call it before finishing every phase. Convoy fixes the report path; do not use write or edit for the report. In read-only phases this is the only permitted report write. Scoring agents pass dimensions, mustFix, gaps, and confidence; never invent score or verdict.",
  args: {
    markdown: tool.schema.string(),
    dimensions: tool.schema.object({ prd: tool.schema.number(), tests: tool.schema.number(), security: tool.schema.number(), maintainability: tool.schema.number(), operational: tool.schema.number(), scope: tool.schema.number() }).optional(),
    mustFix: tool.schema.array(tool.schema.string()).optional(),
    gaps: tool.schema.object({ prd: tool.schema.string().optional(), tests: tool.schema.string().optional(), security: tool.schema.string().optional(), maintainability: tool.schema.string().optional(), operational: tool.schema.string().optional(), scope: tool.schema.string().optional() }).optional(),
    confidence: tool.schema.enum(["high", "medium", "low"]).optional(),
  },
  async execute(args, context) {
    const url = ${url}
    const token = ${token}
    try {
      const response = await fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: "Bearer " + token },
        body: JSON.stringify({ sessionID: context?.sessionID, payload: args }),
        signal: context?.abort,
      })
      const body = await response.json().catch(() => ({}))
      if (!response.ok) throw new Error(typeof body?.error === "string" ? body.error : "report bridge returned " + response.status)
      return typeof body?.message === "string" ? body.message : "Report saved."
    } catch (error) {
      throw new Error("write_report failed: " + (error instanceof Error ? error.message : String(error)))
    }
  },
})
`
}

const fallbackWriteReportToolSource = writeReportToolSource(`process.env.${reportUrlEnv}`, `process.env.${reportTokenEnv}`)
